repositoryUrl: https://github.com/gsmlg-dev/ui5-webcomponents.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - "prepareCmd": >-
        echo ${nextRelease.version};
        node .github/actions/rename.js;
        npx lerna link;
        npm install;
        npm run build;
        npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN";
      "publishCmd": "node .github/actions/release.js --version ${nextRelease.version}"
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - master
  - next
  - next-major
  - { name: "beta", prerelease: true }
  - { name: "alpha", prerelease: true }
