name: Publish prerelease

on:
  push:
    branches:
      - main
jobs:
  build:
    if: "contains(github.event.head_commit.message, '#prerelease')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install
      run: yarn

    - name: Auth
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        node ./.github/actions/rename.js
        node ./.github/actions/pre-release.js

